version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: pip install platformio && platformio ci firmware/ --project-conf=firmware/platoformio.ini
workflows:
  version: 2
  build:
    jobs:
      - build
