version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run: pip install -U platformio && platformio ci firmware/ --project-conf=firmware/platoformio.ini
workflows:
  version: 2
  build:
    jobs:
      - build
