version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: pip install --user platformio && /home/circleci/.local/bin/platformio ci project/firmware/ --project-conf=project/firmware/platoformio.ini
workflows:
  version: 2
  build:
    jobs:
      - build
